name: CI ppeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
  steps:
    - uses: actions/checkout@v3
    - name: Starting Node.js ${{matrix.node-version}}
      uses: actions/checkout@v3
      with:
        node-version: ${{matrix.node-version}}
    - name: install modules
      run: npm install
    -name: lint project
      run: npm run lint
    -name: build project
      run: npm run build